version: "3.4"
services:
  api:
    image: rf-api:prod
    build:
      target: build
    container_name: api
    volumes:
      - "./src:/usr/src:delegated"
      - /usr/node_modules
    command: ["npm", "run", "debug"]
