version: "3.4"
services:
  api:
    image: api:prod
    build:
      context: .
      target: build
    container_name: api
    volumes:
      - /usr/node_modules
    command: ["node", "dist/server.js"]
